repositoryUrl: https://github.com/Jenny-Jiani/Jenny-Jiani.github.io/blob/master

docFullPath: https://jenny-jiani.github.io/
docHomePage: /programming/

parameters: /parameters/
enumerations: parameters/enum/
parameters-reference: /parameters/reference/

programming: /programming/

c-cplusplus: /programming/c-cplusplus/
c-cplusplus-api-reference: /programming/c-cplusplus/api-reference/
c-functions: /programming/c-cplusplus/api-reference/c-functions/
cpp-methods: /programming/c-cplusplus/api-reference/c-label-recognition-class/
c-cplusplus-structs: /programming/c-cplusplus/structs/

c-cplusplus-release-notes: /programming/c-cplusplus/release-notes/

assets: /assets/
edit_icon: /assets/img-icon/edit-icon.png
smile_icon: /assets/img-icon/icon-smile.png
sad_icon: /assets/img-icon/icon-sad.png
dbr_icon: /assets/img-icon/icon-dbr.svg
dwt_icon: /assets/img-icon/icon-dwt.svg
dnt_icon: /assets/img-icon/icon-dnt.svg

baseurl: "/"
plugins:
  - jemoji