repositoryUrl: https://github.com/Dynamsoft/web-twain-docs/master

docHomePage: /web-twain/docs/
dynamsoft_logo: /web-twain/docs/assets/img-icon/dynamsoft-logo.png
dwt_logo: /web-twain/docs/assets/img-icon/dwt-logo.png
edit_icon: /web-twain/docs/assets/img-icon/edit-icon.png

assets: /web-twain/docs/assets/
_includes: /web-twain/docs/_includes/
_layouts: /web-twain/docs/_layouts/
about: /web-twain/docs/about/
getstarted: /web-twain/docs/getstarted/
indepth: /web-twain/docs/indepth/
info: /web-twain/docs/info/
theme: jekyll-theme-cayman