repositoryUrl: https://github.com/Jenny-Jiani/Jenny-Jiani.github.io/blob/master
firstLevelUrl: /
repository: Dynamsoft/web-twain-docs
docFullPath: https://jenny-jiani.github.io/
productUrl: https://www.dynamsoft.com/Products/WebTWAIN_Overview.aspx
productName: Dynamic Web TWAIN
docHomePage: /
dynamsoft_logo: /assets/img-icon/dynamsoft-logo.png
dwt_logo: /assets/img-icon/dwt-logo.png
edit_icon: /assets/img-icon/edit-icon.png

assets: /assets/
_includes: /_includes/
_layouts: /_layouts/
about: /about/
getstarted: /getstarted/
indepth: /indepth/
info: /info/

dynamsoft_logo: /assets/img-icon/dynamsoft-logo.png
dbr_logo: /assets/img-icon/dbr-logo.png
edit_icon: /assets/img-icon/edit-icon.png
smile_icon: /assets/img-icon/icon-smile.png
sad_icon: /assets/img-icon/icon-sad.png
dbr_icon: /assets/img-icon/icon-dbr.svg
dwt_icon: /assets/img-icon/icon-dwt.svg
dnt_icon: /assets/img-icon/icon-dnt.svg

baseurl: /

theme: jekyll-theme-cayman

collections:
  blogs:
    output: true
    premalink: /:collection/:path

pagination:
  collection: blogs
  enabled: true
  debug: false
  title: ':title - 奚西溪的小天地'
  per_page: 10
  permalink: '/page/:num'
  sort_field: 'date'
  sort_reverse: true
