repositoryUrl: https://github.com/Jenny-Jiani/Jenny-Jiani.github.io/blob/master

docFullPath: https://jenny-jiani.github.io/
docHomePage: /use-cases/

COVID-19: /use-cases/covid-19/

assets: /assets/
edit_icon: /assets/img-icon/edit-icon.png
smile_icon: /assets/img-icon/icon-smile.png
sad_icon: /assets/img-icon/icon-sad.png
dbr_icon: /assets/img-icon/icon-dbr.svg
dwt_icon: /assets/img-icon/icon-dwt.svg
dnt_icon: /assets/img-icon/icon-dnt.svg

baseurl: "/"
plugins:
  - jemoji