repositoryUrl: https://github.com/Jenny-Jiani/Jenny-Jiani.github.io/blob/master
repository: /
docRootName: Dynamsoft License Tracking

docFullPath: https://jenny-jiani.github.io/
firstLevelUrl: /
docHomePage: /

productUrl: https://www.dynamsoft.com/Products/Dynamic-Barcode-Reader.aspx
# productName: Dynamsoft Barcode Reader

imagecore-viewer-module: /imagecore-viewer-module/
twainscan-module: /twainscan-module/
camera-module: /camera-module/
pdf-module: /pdf-module/
ocr-module: /ocr-module/
troubleshooting: /troubleshooting/
upgrade-dotnet-twain: /upgrade-dotnet-twain/
api-reference: /api-reference/
release-notes: /release-notes/

assets: /assets/
edit_icon: /assets/img-icon/edit-icon.png
smile_icon: /assets/img-icon/icon-smile.png
sad_icon: /assets/img-icon/icon-sad.png
dbr_icon: /assets/img-icon/icon-dbr.svg
dwt_icon: /assets/img-icon/icon-dwt.svg
dnt_icon: /assets/img-icon/icon-dnt.svg

baseurl: ""
plugins:
  - jemoji